#ipv6:

spring:
  datasource:
    url: jdbc:postgresql://db.pjgjngwqlibmpyksontz.supabase.co:5432/postgres
    username: postgres
    password: LA5h7jXh4fh2k1mN
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




#ipv 4:

#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
#  datasource:
#    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
#    username: postgres.pjgjngwqlibmpyksontz
#    password: LA5h7jXh4fh2k1mN
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


#spring:
#  profiles:
#    active: dev
#
#  mvc:
#    throw-exception-if-no-handler-found: true
#
#  web:
#    resources:
#      add-mappings: false
#
#  security:
#    jwt:
#      secret-key: 53cr37
#      expire-length: 3600000