#ipv6:

#spring:
#  datasource:
#    url: jdbc:postgresql://db.ieojlfjqjvwxwuwldpsa.supabase.co:5432/postgres?
#    username: postgres
#    password: LA5h7jXh4fh2k1mN
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true




#ipv 4:

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
  file:
    upload-dir: \uploads #caminho para o envio de arquivos
  web:
    resources:
      add-mappings: false
  datasource:
#    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
#    username: postgres.ulrmtndiqhrdlnzuzmkd
#    password: XvP92$DgDhh#Exk
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB




#spring:
#  profiles:
#    active: dev
#
#  mvc:
#    throw-exception-if-no-handler-found: true
#
#  web:
#    resources:
#      add-mappings: false
#
#  security:
#    jwt:
#      secret-key: 53cr37
#      expire-length: 3600000